Repository americanas-go/log, pull requests merged in 2021-05, with the labels that each got.

#10 feat: add default option for zap and zerolog
  contrib/go.uber.org/zap.v1/logger.go
  contrib/go.uber.org/zap.v1/options.go
  contrib/rs/zerolog.v1/logger.go
  contrib/rs/zerolog.v1/options.go
  contrib/sirupsen/logrus.v1/options.go
Labels: enhancement

#19 fix: level option in zerolog
  contrib/rs/zerolog.v1/logger.go
  contrib/rs/zerolog.v1/options.go
Labels: bug

#25 fix: rename cloudwatch formatter constructor
  contrib/sirupsen/logrus.v1/formatter/cloudwatch/formatter.go
Labels: bug

#9 docs: update README.md
  README.md
  contrib/go.uber.org/zap.v1/README.md
  contrib/rs/zerolog.v1/README.md
  contrib/sirupsen/logrus.v1/README.md
Labels: documentation

#27 docs: adds a pkg.go.dev badge to readme
  README.md
Labels: documentation
